= CalConnect Standard: DAV Server Information Object

This work item belongs to CalConnect TC CALSPAM.

image:https://github.com/CalConnect/cc-server-info/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-server-info/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-server-info/[CalConnect: DAV Server Information Object (HTML)]

== General

This document specifies the DAV Server Information Object.

The document is published as the following:

* CalConnect CC 51022
* IETF draft-douglass-server-info


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-server-info/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== License

Copyright its respective authors and CalConnect.
