== Server Information Document Use

A host will make the document available through one or more methods. Depending
upon the endpoint and method of retrieval the retrieved document may describe
one or more applications.

If a document provides information for more than one application it SHOULD
contain information allowing clients to obtain information about each individual
application only. This allows a client to determine what the actual limits and
features are for the specific application.

=== Server Information Location and Retrieval

==== Server Information Retrieval

The document may be retrieved from the server by including the server-info-token
header field with a value of "*" any request to the server.

The server MUST respond to such a request by including a LINK header field with
a reltype of "server-info", a token parameter with the current token value and
the url being the location of the document.

Following that a GET may be executed by the client against that URL, specifying
a content type in the ACCEPT header field of "application/server-info+xml".

Clients SHOULD retrieve the document in the context of a session and
applications SHOULD ensure the context is appropriate. Values in the returned
document may differ depending on who is authenticated so a server SHOULD require
authentication before returning server information for an authenticated
application.

==== Server Information Synchronization

While server features may not change frequently it may be important for clients
to react rapidly when server features or limits change. Polling for server
feature changes is undesirable so this specification allows clients to check for
such changes during normal operations.

Clients SHOULD include the server-info-token header field with the current
stored value of the token from the document in requests to the server.

The server MUST add the link header field to the response when the tokens do not
match.

===== Header Field: server-info-token

The server-info-token header field takes as a value the current value of the
token element in the server-info document or the value "*".

This header field may be included in a request at any time a client feels
appropriate.

===== Header Field: link

The link header field is defined in <<RFC5988>>. The target IRI as defined by
that specification will be the location of the server information document. The
"reltype" parameter will have the value "server-info".

Additionally, there will be a "token" parameter which has a quoted token as the
value.

This header field may be included in a response at any time a server feels
appropriate.

The link header field MUST be returned in response to:

* An OPTIONS request where the server-info-token header is absent or it's value
does not match. * Any request with the server-info-token header field where the
value of the header field does not math the current token value.

The link header field SHOULD be returned when a client:

* Attempts to use an unsupported feature.
* Misuses a feature according to the server info document.
* Exceeds a limit defined in the document.

If the server returns a link header field as part of the response it is an
indication to the client that it SHOULD fetch a new copy of the server
information document.

The following is an example of a link header field - folded to fit on the page

[source%unnumbered]
----
Link: </dav/principals/.server-info>; rel="server-info";
 token="7140903ee1b57d0752a7d8da774a398b10de5868"
----
